frontend/models/Adjudicator.php
<?php

namespace frontend\models;
use backend\models\Config;
use kartik\helpers\Html;

use Yii;

/**
 * This is the model class for table "adjudicator".
 *
 * @property integer $id
 * @property string $name
 * @property string $institution
 * @property integer $initial_score
 * @property string $unique_code
 *
 * @property DebateAdj[] $debateAdjs
 * @property Debate[] $debates
 * @property Feedback[] $feedbacks
 */
class Adjudicator extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'adjudicator';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'name', 'institution', 'initial_score', 'unique_code'], 'required'],
            [['id', 'initial_score'], 'integer'],
            [['name'], 'string', 'max' => 30],
            [['institution'], 'string', 'max' => 20],
            [['unique_code'], 'string', 'max' => 3]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'institution' => 'Institution',
            'initial_score' => 'Initial Score',
            'unique_code' => 'Unique Code',
        ];
    }

    public function getNameInst()
    {
        return $this->name.' ('.$this->institution.')';
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDebateAdjs()
    {
        return $this->hasMany(DebateAdj::className(), ['adjudicator_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDebates()
    {
        return $this->hasMany(Debate::className(), ['id' => 'debate_id'])->viaTable('debate_adj', ['adjudicator_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFeedbacks()
    {
        return $this->hasMany(Feedback::className(), ['giver_adj_id' => 'id']);
    }

    public function generateUniqueCode(){
        $this->unique_code = '000';

        do{
            $unique_code = rand()%899+100;

            $teams = Team::find()->where(['unique_code'=>$unique_code])->one();
            $adjs = Adjudicator::find()->where(['unique_code'=>$unique_code])->one();

            if(!$teams && !$adjs) $this->unique_code = $unique_code;
        }while($this->unique_code == '000');
    }

    public function getMissingFeedback(){
        $config = Yii::$app->params['config'];
        $sql = "SELECT COUNT(*) FROM debate_adj WHERE adj_id = {$this->id}";

        $sql_append = ' AND status IN (';
        if($config['chair_to'] != '?') $sql_append .= "'c',";
        if($config['panel_to'] != '?') $sql_append .= "'p',";
        if($config['trainee_to'] != '?') $sql_append .= "'t',";
        $sql_append .= "'z')";

        $sql_append .= " AND debate_id NOT IN (SELECT dac.debate_id FROM debate_adj dac WHERE dac.adj_id = {$this->id} AND (SELECT COUNT(*) FROM debate_adj dax WHERE dax.debate_id = dac.debate_id) = 1)";

        $utang = Yii::$app->db->createCommand($sql.$sql_append)->queryScalar();

        return $utang -  Yii::$app->db->createCommand("SELECT COUNT(DISTINCT round) FROM feedback WHERE giver_adj_id = {$this->id}")->queryScalar();
    }

    public function getDisplay(){
        $missing = $this->missingFeedback;
        if($missing > 0) return $this->nameInst.' '.Html::badge($this->missingFeedback);
        else return $this->nameInst;
    }

    public function import(){
        $config = Yii::$app->params['config'];

        if($config['system'] == 'tabbycat'){
            $connection = \Yii::$app->tabbycat;
     
            $model = $connection->createCommand('
                SELECT p.id "id", p.name "name", ai.code "institution", a.test_score "initial_score"
                FROM debate_adjudicator a,
                    debate_person p,
                    debate_institution ai
                WHERE a.person_ptr_id = p.id
                    AND a.institution_id = ai.id
            ');
        }
        else if($config['system'] == 'tabbie'){
            $connection = \Yii::$app->tabbie;

            $model = $connection->createCommand('
                SELECT `adjud_id` id,`adjud_name` name,`univ_code` institution,`ranking` initial_score
                FROM `adjudicator` a JOIN `university` u ON a.`univ_id`=u.`univ_id`
            ');
        }

        $result = $model->queryAll();
        
        return $result;
    }
}

backend/controllers/AdjudicatorController.php
<?php

namespace backend\controllers;

use Yii;
use frontend\models\Adjudicator;
use backend\models\AdjudicatorSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * AdjudicatorController implements the CRUD actions for Adjudicator model.
 */
class AdjudicatorController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Adjudicator models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AdjudicatorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Adjudicator model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionImport()
    {
        $arr = Adjudicator::import();
        foreach($arr as $r){
            $model = Adjudicator::findOne($r['id']);
            if($model == null) $model = new Adjudicator();
            $model->id = $r['id'];
            $model->name = $r['name'];
            $model->institution = $r['institution'];
            $model->initial_score = $r['initial_score'];
            $model->generateUniqueCode();
            // echo '<pre>';
            // print_r($model->attributes);
            // echo '</pre>';
            $model->save(false);
        }
        $this->redirect('index');
    }

    /**
     * Creates a new Adjudicator model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Adjudicator();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Adjudicator model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionStatus($id){
        $model = $this->findModel($id);
        if($model->status == 'o') $model->status = 'l';
        else if($model->status == 'l') $model->status = 'o';
        $model->save();
        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing Adjudicator model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Adjudicator model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Adjudicator the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Adjudicator::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/adjudicator/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Adjudicator */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="adjudicator-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id')->textInput() ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'institution')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'initial_score')->textInput() ?>

    <?= $form->field($model, 'unique_code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/adjudicator/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\AdjudicatorSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="adjudicator-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'institution') ?>

    <?= $form->field($model, 'initial_score') ?>

    <?= $form->field($model, 'unique_code') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/adjudicator/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\Adjudicator */

$this->title = 'Create Adjudicator';
$this->params['breadcrumbs'][] = ['label' => 'Adjudicators', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="adjudicator-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/adjudicator/index.php
<?php

use kartik\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\ButtonGroup;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\AdjudicatorSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Adjudicators';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="adjudicator-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= ButtonGroup::widget([
            'buttons' => [
                Html::a('Create Adjudicator', ['create'], ['class' => 'btn btn-primary']),
                Html::a('Import Debate Data', ['import'], ['class' => 'btn btn-success']),
            ]
        ]) ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'institution',
            'initial_score',
            'unique_code',
            [
                'label'=>'Status',
                'format'=>'raw',
                'value'=> function($model){
                    if($model->status == 'o') return Html::a(Html::bsLabel('OPEN', Html::TYPE_SUCCESS), ['adjudicator/status', 'id'=>$model->id]);
                    else if($model->status == 'l') return Html::a(Html::bsLabel('LOCK', Html::TYPE_DANGER), ['adjudicator/status', 'id'=>$model->id]);
                }
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

backend/views/adjudicator/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Adjudicator */

$this->title = 'Update Adjudicator: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Adjudicators', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="adjudicator-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/adjudicator/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\Adjudicator */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Adjudicators', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="adjudicator-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'institution',
            'initial_score',
            'unique_code',
            'status',
        ],
    ]) ?>

</div>