frontend/models/Round.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "round".
 *
 * @property integer $round
 * @property string $status
 * @property string $start_at
 * @property string $motion
 *
 * @property DebateTeam[] $debateTeams
 * @property Feedback[] $feedbacks
 */
class Round extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'round';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['start_at'], 'safe'],
            [['motion'], 'string'],
            [['status'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'round' => 'Round',
            'status' => 'Status',
            'start_at' => 'Start At',
            'motion' => 'Motion',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDebateTeams()
    {
        return $this->hasMany(DebateTeam::className(), ['round' => 'round']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFeedbacks()
    {
        return $this->hasMany(Feedback::className(), ['round' => 'round']);
    }

    public function import($round){
        $config = Yii::$app->params['config'];

        if($config['system'] == 'tabbycat'){
            $connection = \Yii::$app->tabbycat;
     
            $model1 = $connection->createCommand("
                SELECT d.id id, d.round_id round, v.name room, t1.team_id team_id_og, t2.team_id team_id_oo, '' team_id_cg, '' team_id_co
                FROM (((debate_debate d JOIN debate_debateteam t1 ON d.id=t1.debate_id)
                    JOIN debate_debateteam t2 ON d.id=t2.debate_id)
                    JOIN debate_venue v ON v.id=d.venue_id)
                WHERE t1.position='A' AND t2.position='N' AND d.round_id={$round}
            ");
            $model2 = $connection->createCommand("
                SELECT d.id debate_id, adjudicator_id adj_id, LOWER(type) status
                FROM debate_debateadjudicator a JOIN debate_debate d ON d.id=a.debate_id
                WHERE d.round_id = {$round}
            ");
        }
        else if($config['system'] == 'tabbie'){
            $connection = \Yii::$app->tabbie;

            $model1 = $connection->createCommand("
                SELECT `debate_id` id, '{$round}' round, `venue_name` room, `og` team_id_og, `oo` team_id_oo, `cg` team_id_cg, `co` team_id_co
                FROM `draw_round_{$round}` d JOIN `venue` v ON v.venue_id = d.venue_id
            ");

            $model2 = $connection->createCommand("
                SELECT debate_id, adjud_id adj_id, SUBSTR(`status`, 1,1) `status` FROM `adjud_round_{$round}`
            ");
        }

        $result['debate'] = $model1->queryAll();
        $result['debateAdj'] = $model2->queryAll();
        
        return $result;
    }

    public function getProgressAdj(){
        $config = Yii::$app->params['config'];
        $sql = "SELECT COUNT(*) FROM debate_adj da JOIN debate d ON d.id=da.debate_id WHERE round = {$this->round}";

        $sql_append = ' AND status IN (';
        if($config['chair_to'] != '?') $sql_append .= "'c',";
        if($config['panel_to'] != '?') $sql_append .= "'p',";
        if($config['trainee_to'] != '?') $sql_append .= "'t',";
        $sql_append .= "'z')";

        $adj = Yii::$app->db->createCommand($sql.$sql_append)->queryScalar();
        $feed = Yii::$app->db->createCommand("SELECT COUNT(DISTINCT round) FROM feedback WHERE round = {$this->round} AND giver_adj_id IS NOT NULL")->queryScalar();

        return $adj==0 ? 0 : 100*$feed/$adj;
    }

    public function getProgressTeam(){
        $config = Yii::$app->params['config'];
        $debate = Yii::$app->db->createCommand("SELECT COUNT(*) FROM debate WHERE round={$this->round}")->queryScalar();
        $team = (($config['system'] == 'tabbycat') ? $debate*2 : (($config['system'] == '3tab') ? $debate*2 : $debate*4));
        $feed = Yii::$app->db->createCommand("SELECT COUNT(DISTINCT round) FROM feedback WHERE round = {$this->round} AND giver_team_id IS NOT NULL")->queryScalar();

        return $team==0 ? 0 : 100*$feed/$team;
    }

    public function getPrev(){
        return $this->findOne($this->round-1);
    }

    public function getNext(){
        return $this->findOne($this->round+1);
    }
}

backend/controllers/RoundController.php
<?php

namespace backend\controllers;

use Yii;
use frontend\models\Round;
use frontend\models\Debate;
use frontend\models\DebateAdj;
use frontend\models\Adjudicator;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * RoundController implements the CRUD actions for Round model.
 */
class RoundController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Round models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Round::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Round model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $debate = Debate::find();
        $adj = new ActiveDataProvider([
            'query' => DebateAdj::find()->leftJoin(['debate'=>$debate], 'debate.id = debate_id')->where(['round'=>$id])->orderBy('room, status'),
            'pagination'=>false,
        ]);
        return $this->render('view', [
            'model' => $this->findModel($id),
            'adj' => $adj,
        ]);
    }

    public function actionPending($id){
        $model = $this->findModel($id);
        $model->status = 'p';
        $model->save();
        $this->redirect('index');
    }

    public function actionOpen($id){
        $model = $this->findModel($id);
        $model->status = 'o';
        $model->save();
        $this->redirect('index');
    }

    public function actionSilent($id){
        $model = $this->findModel($id);
        $model->status = 's';
        $model->save();
        $this->redirect('index');
    }

    public function actionImport($round){
        $arr = Round::import($round);
        foreach($arr['debate'] as $r){
            $model = Debate::findOne($r['id']);
            if($model == null) $model = new Debate();
            $model->id = $r['id'];
            $model->round = $r['round'];
            $model->room = $r['room'];
            $model->team_id_og = $r['team_id_og'];
            $model->team_id_oo = $r['team_id_oo'];
            $model->team_id_cg = $r['team_id_cg'];
            $model->team_id_co = $r['team_id_co'];
            
            $model->save(false);

            foreach($model->debateAdj as $a) $a->delete();
        }
        foreach($arr['debateAdj'] as $r){
            $model = new DebateAdj();
            $model->debate_id = $r['debate_id'];
            $model->adj_id = $r['adj_id'];
            $model->status = $r['status'];

            $model->save(false);
        }
        $this->redirect('index');
    }

    public function actionUpdatealloc($adj_id, $debate_id){
        $model = DebateAdj::find()->where(['adj_id'=>$adj_id, 'debate_id'=>$debate_id])->one();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->debate->round]);
        } else {
            $adj = Adjudicator::find()->all();
            $debate = Debate::find()->where(['round'=>$model->debate->round])->all();
            return $this->render('updatealloc', [
                'model' => $model,
                'adj' => $adj,
                'debate' => $debate,
            ]);
        }
    }

    /**
     * Creates a new Round model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Round();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->round]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Round model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->round]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Round model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Round model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Round the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Round::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/round/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Round */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="round-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'start_at')->textInput() ?>

    <?= $form->field($model, 'motion')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/round/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\Round */

$this->title = 'Create Round';
$this->params['breadcrumbs'][] = ['label' => 'Rounds', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="round-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/round/index.php
<?php

use kartik\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\ButtonGroup;
use yii\bootstrap\Progress;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Rounds';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="round-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Round', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'round',
            'start_at',
            [
                'attribute'=>'status',
                'format'=>'raw',
                'value'=>function($model){
                    $s = $model->status;
                    return ButtonGroup::widget([
                        'buttons' => [
                            Html::a(Html::icon('hourglass').' Pending', ['round/pending', 'id'=>$model->round],['class'=> ($s=='p')?'btn btn-warning':'btn btn-default']),
                            Html::a(Html::icon('ok').' Open', ['round/open', 'id'=>$model->round],['class'=> ($s=='o')?'btn btn-primary':'btn btn-default']),
                            Html::a(Html::icon('volume-off').' Silent', ['round/silent', 'id'=>$model->round],['class'=> ($s=='s')?'btn btn-danger':'btn btn-default']),
                        ]
                    ]);
                },
                'options' => [
                    'column'
                ]
            ],
            [
                'attribute'=>'progressTeam',
                'format'=>'raw',
                'value'=>function($model){
                    return Progress::widget([
                        'percent' => $model->progressTeam,
                        'barOptions' => ['class' => 'progress-bar-success'],
                        'options' => ['class' => 'active progress-striped'],
                        'label' => round($model->progressTeam,2).'%',
                    ]);
                }
            ],
            [
                'attribute'=>'progressAdj',
                'format'=>'raw',
                'value'=>function($model){
                    return Progress::widget([
                        'percent' => $model->progressAdj,
                        'barOptions' => ['class' => 'progress-bar-primary'],
                        'options' => ['class' => 'active progress-striped'],
                        'label' => round($model->progressAdj,2).'%',
                    ]);
                }
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

backend/views/round/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Round */

$this->title = 'Update Round: ' . ' ' . $model->round;
$this->params['breadcrumbs'][] = ['label' => 'Rounds', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->round, 'url' => ['view', 'id' => $model->round]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="round-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/round/updatealloc.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\widgets\Select2;

/* @var $this yii\web\View */
/* @var $model frontend\models\Round */

$this->title = 'Update Allocation ' . ' ' . $model->debate->id;
$this->params['breadcrumbs'][] = ['label' => 'Rounds', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Rounds'.$model->debate->round, 'url' => ['view', 'id' => $model->debate->round]];
$this->params['breadcrumbs'][] = 'Update Allocation';
?>
<div class="round-update">

    <h1><?= Html::encode($this->title) ?></h1>

	<div class="round-form">

	    <?php $form = ActiveForm::begin(); ?>

		<?= $form->field($model, 'adj_id')->widget(Select2::classname(),[
			'data' => ArrayHelper::map($adj, 'id', 'nameInst')
		]) ?>

	    <?= $form->field($model, 'debate_id')->widget(Select2::classname(),[
			'data' => ArrayHelper::map($debate, 'id', 'allocation')
		]) ?>

	    <?= $form->field($model, 'status')->dropdownList(['c' => 'Chair','p' => 'Panelist','t' => 'Trainee']) ?>

	    <div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>

	    <?php ActiveForm::end(); ?>

	</div>

</div>

backend/views/round/view.php
<?php

use kartik\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;
use yii\bootstrap\ButtonGroup;

/* @var $this yii\web\View */
/* @var $model frontend\models\Round */

$this->title = $model->round;
$this->params['breadcrumbs'][] = ['label' => 'Rounds', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="round-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= ButtonGroup::widget([
            'buttons' => [
                Html::a('Edit Motion', ['update', 'id' => $model->round], ['class' => 'btn btn-primary']),
                Html::a('Import Debate Data', ['import', 'round' => $model->round], ['class' => 'btn btn-success']),
            ]
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'round',
            'status',
            'start_at',
            'motion:ntext',
        ],
    ]) ?>

    <?= GridView::widget([
        'dataProvider' => $adj,
        'tableOptions'=>['class'=>'table table-striped', 'style'=>'font-size:small;'],
        'columns' => [
            'debate.round',
            'debate.room',
            'debate.teamOG.team_name',
            'debate.teamOO.team_name',
            'debate.teamCG.team_name',
            'debate.teamCO.team_name',
            'adjudicator.nameInst',
            [
                'attribute'=>'status',
                'format'=>'raw',
                'value'=>function($model){
                    return $model->status=='c' ? Html::bsLabel('Chair', Html::TYPE_SUCCESS) : 
                        ($model->status=='p' ? Html::bsLabel('Panel', Html::TYPE_INFO) : 
                            ($model->status=='t' ? Html::bsLabel('Trainee', Html::TYPE_WARNING) : 
                                Html::bsLabel('Unidentified', Html::TYPE_DANGER)));
                }
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}',
                'buttons' => [
                    'update' => function ($url, $model, $key) {
                        return Html::a(Html::icon('pencil'), 
                            ['updatealloc', 'adj_id'=>$model->adj_id,'debate_id'=>$model->debate_id]
                        );
                    }
                ],
            ],
        ],
    ]);
    ?>
</div>