frontend/models/LanguageStatus.php
<?php

namespace frontend\models;

use Yii;
use kartik\helpers\Html;

/**
 * This is the model class for table "language_status".
 *
 * @property integer $team_id
 * @property string $speaker_1_applying_as
 * @property string $speaker_1_status
 * @property string $speaker_1_interview
 * @property string $speaker_2_applying_as
 * @property string $speaker_2_status
 * @property string $speaker_2_interview
 * @property string $speaker_3_applying_as
 * @property string $speaker_3_status
 * @property string $speaker_3_interview
 *
 * @property Team $team
 * @property LanguageStatusAppeal[] $languageStatusAppeals
 */
class LanguageStatus extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'language_status';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['team_id'], 'required'],
            [['team_id'], 'integer'],
            [['speaker_1_applying_as', 'speaker_2_applying_as', 'speaker_3_applying_as'], 'string', 'max' => 10],
            [['speaker_1_status', 'speaker_2_status', 'speaker_3_status'], 'string', 'max' => 1],
            [['speaker_1_interview', 'speaker_2_interview', 'speaker_3_interview'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'team_id' => 'Team ID',
            'speaker_1_applying_as' => '#1 would like to be considered as',
            'speaker_1_status' => 'Speaker 1 Status',
            'speaker_1_interview' => 'Speaker 1 Interview',
            'speaker_2_applying_as' => '#2 would like to be considered as',
            'speaker_2_status' => 'Speaker 2 Status',
            'speaker_2_interview' => 'Speaker 2 Interview',
            'speaker_3_applying_as' => '#3 would like to be considered as',
            'speaker_3_status' => 'Speaker 3 Status',
            'speaker_3_interview' => 'Speaker 3 Interview',
            'd1s' => '',
            'd2s' => '',
            'd3s' => ''
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTeam()
    {
        return $this->hasOne(Team::className(), ['id' => 'team_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAppeals()
    {
        return $this->hasMany(LanguageStatusAppeal::className(), ['team_id' => 'team_id']);
    }

    private function display($language, $status){
        $color = Html::TYPE_DEFAULT;
        if($language == 'efl') $color = Html::TYPE_SUCCESS;
        else if($language == 'esl') $color = Html::TYPE_PRIMARY;
        else if($language == 'novice') $color = Html::TYPE_INFO;

        $statuscolor = Html::TYPE_DEFAULT;
        if($status == 'a') $statuscolor = Html::TYPE_SUCCESS;
        else if($status == 'i') $statuscolor = Html::TYPE_WARNING;
        else if($status == 'r') $statuscolor = Html::TYPE_DANGER;

        return Html::bsLabel($language, $color) . ' ' . Html::bsLabel($status, $statuscolor);
    }

    public function getD1s(){
        return $this->display($this->speaker_1_applying_as, $this->speaker_1_status);
    }

    public function getD2s(){
        return $this->display($this->speaker_2_applying_as, $this->speaker_2_status);
    }

    public function getD3s(){
        return $this->display($this->speaker_3_applying_as, $this->speaker_3_status);
    }

    public function getAppealed()
    {
        return Html::bsLabel(count($this->appeals));
    }
}

backend/controllers/LanguagestatusController.php
<?php

namespace backend\controllers;
use Yii;
use frontend\models\Team;
use frontend\models\LanguageStatus;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;

class LanguagestatusController extends \yii\web\Controller
{
    public function actionApprove($id, $status, $speaker)
    {
        $model = $this->findModel($id)->languageStatus;

        switch($speaker){
            case 1 : $model->speaker_1_status = $status; break;
            case 2 : $model->speaker_2_status = $status; break;
            case 3 : $model->speaker_3_status = $status; break;
        }

        $model->save();

        return $this->redirect('view', $id);
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Team::find()->orderBy('team_name')->where('id IN (SELECT team_id FROM language_status)'),
            'pagination' => false,
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        $questions = explode(';', Yii::$app->params['config']['language_status_interview_questions']);
        return $this->render('view', [
            'model' => $this->findModel($id),
            'questions' => $questions,
        ]);
    }

    protected function findModel($id)
    {
        if (($model = Team::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/LanguagestatusController.php
<?php
namespace frontend\controllers;

use frontend\models\Team;
use frontend\models\Adjudicator;
use frontend\models\LanguageStatusAppeal;
use frontend\models\LanguageStatus;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use Yii;

class LanguagestatusController extends \yii\web\Controller
{
    public function actionAppeal($id)
    {
        $model = $this->findTeam($id);
        $appeal = new LanguageStatusAppeal();

        if(isset($_POST['giver']) && isset($_POST['unique_code'])){
            $team = Team::find()->where(['team_name'=>$_POST['giver']])->one();

            if($team == null){
                $adj = Adjudicator::find()->where("CONCAT(name,' (',institution,')') = '{$_POST['giver']}'")->one();
                $appeal->giver_adj_id = $adj->id;
                $unique_code = $adj->unique_code;
            }
            $appeal->giver_team_id = $team->id;
            $unique_code = $team->unique_code;
            $appeal->to_whom = $_POST['LanguageStatusAppeal']['to_whom'];
            $appeal->appeal = $_POST['LanguageStatusAppeal']['appeal'];

            if($_POST['unique_code'] === $unique_code){
                $appeal->team_id = $id;

                if($appeal->save())
                    Yii::$app->session->setFlash('success', 'Appeal submitted! Thank you!');
                    return $this->redirect(['index']);
            } else {
                Yii::$app->session->setFlash('error', 'Wrong Unique Code. Try Again!');
            }
        } else if (isset($_POST['giver']) && isset($_POST['unique_code']) && isset($_POST['LanguageStatusAppeal'])){
            Yii::$app->session->setFlash('error', 'Identify Yourself! Who are you?');
        }

        $teams = Team::find()->orderBy('team_name')->all();
        $adjs = Adjudicator::find()->orderBy('name')->all();

        return $this->render('appeal', ['model'=>$model, 'appeal'=> $appeal, 'teams'=>$teams, 'adjs'=>$adjs]);
    }

    public function actionApply($id)
    {
        $config = Yii::$app->params['config'];

        $model = $this->findTeam($id);
        if($model->languageStatus != null) throw new ForbiddenHttpException('You have registered! Contact admin if this is a mistake');
        $langstats = new LanguageStatus;
        $langstats->team_id = $model->id;

        

        if ($langstats->load(Yii::$app->request->post())) {
            $langstats->speaker_1_status = 'r';
            $langstats->speaker_1_interview = implode(',', $langstats->speaker_1_interview);

            $langstats->speaker_2_status = 'r';
            $langstats->speaker_2_interview = implode(',', $langstats->speaker_2_interview);

            $langstats->speaker_3_status = 'r';
            $langstats->speaker_3_interview = implode(',', $langstats->speaker_3_interview);
            
            if($langstats->save())
                return $this->redirect(['index']);
        } else {
            $statuses = explode(',', $config['language_status']);
            $statuses = array_combine($statuses, $statuses);
            
            if($config['language_status_interview_questions'] == '' || $config['language_status_interview_questions'] == null) $questions = [];
            else $questions = explode(';', $config['language_status_interview_questions']);

            return $this->render('apply', ['model'=>$model, 'langstats'=>$langstats, 'statuses'=>$statuses, 'questions'=>$questions]);
        }

        
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Team::find()->orderBy('team_name'),
            'pagination' => false,
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    private function findTeam($id){
        $team = Team::findOne($id);
        if($team == null) throw new NotFoundHttpException('Team Not Found');
        return $team;
    }

}

backend/views/languagestatus/approve.php
<?php
/* @var $this yii\web\View */
?>
<h1>languagestatus/appeal</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

backend/views/languagestatus/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Language Status';
?>
<div class="tag-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'emptyText' => '',
	    'tableOptions' =>['class' => 'table table-striped'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'team_name',
            'debater_1',
            'languageStatus.d1s:raw',
            'debater_2',
            'languageStatus.d2s:raw',
            'debater_3',
            'languageStatus.d3s:raw',
            'languageStatus.appealed:raw:Appealed',

            [
            	'label'=>'',
            	'format'=>'raw',
            	'value'=>function($model){
            		return Html::a('View', ['languagestatus/view', 'id'=>$model->id], ['class'=>'btn btn-default']);
            	}
            ],
        ],
    ]); ?>

</div>

backend/views/languagestatus/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;

$appeals = new ActiveDataProvider([
    'query' => $model->languageStatus->getAppeals(),
    'pagination' => false,
]);

/* @var $this yii\web\View */
/* @var $model frontend\models\LanguageStatus */

$this->title = 'View Language Status for ID #' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Language Statuses', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="language-status-view">

	<div class="row" style="border-bottom:1px grey solid;">
		<div class="col-lg-9">
		    <h2><?= $model->debater_1 ?> <?= $model->languageStatus->d1s ?></h2>

		    <?php
		    	$responses = explode(',', $model->languageStatus->speaker_1_interview);

		    	foreach($questions as $i => $q){
		    		list($x, $a) = explode(':', $q);
		    		$a = explode(',', $a);

		    		echo '<p style="font-weight:bold">'.$x.'</p>';
		    		echo '<p>'.$a[$responses[$i]].'</p>';
		    	}
		    ?>
		</div>

		<div class="col-lg-3">
		    <h1><div class="btn-group">
				<?= Html::a('Appr', ['languagestatus/approve', 'id'=>$model->id, 'status'=>'a', 'speaker'=>1], ['class'=>'btn btn-success']) ?>
				<?= Html::a('Itrvw', ['languagestatus/approve', 'id'=>$model->id, 'status'=>'i', 'speaker'=>1], ['class'=>'btn btn-warning']) ?>
				<?= Html::a('Rjct', ['languagestatus/approve', 'id'=>$model->id, 'status'=>'r', 'speaker'=>1], ['class'=>'btn btn-danger']) ?>
			</div></h1>
		</div>

    	<hr/>
	</div>

	<div class="row" style="border-bottom:1px grey solid;">
		<div class="col-lg-9">
		    <h2><?= $model->debater_2 ?> <?= $model->languageStatus->d2s ?></h2>

		    <?php
		    	$responses = explode(',', $model->languageStatus->speaker_2_interview);

		    	foreach($questions as $i => $q){
		    		list($x, $a) = explode(':', $q);
		    		$a = explode(',', $a);

		    		echo '<p style="font-weight:bold">'.$x.'</p>';
		    		echo '<p>'.$a[$responses[$i]].'</p>';
		    	}
		    ?>
		</div>

		<div class="col-lg-3">
		    <h1><div class="btn-group">
				<?= Html::a('Appr', ['languagestatus/approve', 'id'=>$model->id, 'status'=>'a', 'speaker'=>2], ['class'=>'btn btn-success']) ?>
				<?= Html::a('Itrvw', ['languagestatus/approve', 'id'=>$model->id, 'status'=>'i', 'speaker'=>2], ['class'=>'btn btn-warning']) ?>
				<?= Html::a('Rjct', ['languagestatus/approve', 'id'=>$model->id, 'status'=>'r', 'speaker'=>2], ['class'=>'btn btn-danger']) ?>
			</div></h1>
		</div>

    	<hr/>
	</div>

	<div class="row" style="border-bottom:1px grey solid;">
		<div class="col-lg-9">
		    <h2><?= $model->debater_3 ?> <?= $model->languageStatus->d3s ?></h2>

		    <?php
		    	$responses = explode(',', $model->languageStatus->speaker_3_interview);

		    	foreach($questions as $i => $q){
		    		list($x, $a) = explode(':', $q);
		    		$a = explode(',', $a);

		    		echo '<p style="font-weight:bold">'.$x.'</p>';
		    		echo '<p>'.$a[$responses[$i]].'</p>';
		    	}
		    ?>
		</div>

		<div class="col-lg-3">
		    <h1><div class="btn-group">
				<?= Html::a('Appr', ['languagestatus/approve', 'id'=>$model->id, 'status'=>'a', 'speaker'=>3], ['class'=>'btn btn-success']) ?>
				<?= Html::a('Itrvw', ['languagestatus/approve', 'id'=>$model->id, 'status'=>'i', 'speaker'=>3], ['class'=>'btn btn-warning']) ?>
				<?= Html::a('Rjct', ['languagestatus/approve', 'id'=>$model->id, 'status'=>'r', 'speaker'=>3], ['class'=>'btn btn-danger']) ?>
			</div></h1>
		</div>

    	<hr/>
	</div>

	<h2>Appeals</h2>
	<?= GridView::widget([
        'dataProvider' => $appeals,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'giverAdj.name:raw:ADJ',
            'giverTeam.team_name:raw:TEAM',
            'to_whom',
            'appeal',
        ],
    ]); ?>

</div>